<footer>
	<div class="container">
			<ul class="ft-links-ok">
				<li><a href="#">adverties with us</a></li>
				<li><a href="#">db repoter</a></li>
				<li><a href="#"> trem and condition</a></li>
				<li><a href="#">contact us</a></li>
				<li><a href="#">privacy policy</a></li>
			</ul>
			<p class="od-font">our divisions</p>
			<ul  class="division-ok">
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
				<li><a href="#">odishatv.in</a></li>
			</ul>
			<p class="Copyright-ok">Copyright © Odisha Reporters, All Rights Reserved.</p>
		</div>
</footer>
<script src="js/jquery-3.6.0.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.unveil.js"></script>